### ISSUE TITLE
ReferenceError: window is not defined at EcdsaSignKey.sign (EcdsaSignKey.js:37) 

### ISSUE THREAD

**Issue by ggoldens** [medooze/sframe#13]
After the PR #10 was merged, another hidden bug was discovered. The worker is trying to use do `window.crypto.subtle.sign` in https://github.com/medooze/sframe/blob/master/lib/EcdsaSignKey.js#L37 but `window` is undefined.

A fix is to use directly `crypto.subtle.sign`. I've tried this and seems to be working, but then I see different bug which I'll comment in a different issue.

**Comment by murillo128** [comment]
thanks for the report and the fix!
