### ISSUE TITLE
Wrong IV calculation

### ISSUE THREAD

**Issue by eomara** [medooze/sframe#5]
In https://github.com/medooze/sframe/blob/master/lib/IV.js the IV is constructed from the fromeCounter || KeyId. Unfortunately this will cause IV reuse at the AES-CTR block level. The IV needed to be padded with zeros to avoid this. I suggest to remove the KeyId from the IV and replace it with zeros

**Comment by murillo128** [comment]
The keyId is used as a unique senderId (i.e it should be unique per conference per participant). I will double check the buffer operations, but I think they added padding.

**Comment by murillo128** [comment]
@eomara  in which scenario this would be duplicated? (given that the keyId is unique)

https://jsfiddle.net/jkz5pyt3/

**Comment by eomara** [comment]
Looking at the code again, I think it is fine as long as the counter is in the right 8 bytes and not the other-way around.

**Comment by levlam** [comment]
@murillo128 @eomara "the counter is in the right 8 bytes and not the other-way around" is exactly the issue leading to IV reuse and making the encryption protocol effectively not E2E.

For example, you can see in https://jsfiddle.net/d1uaqm4t/ that if the IV is generated in the current way with two consecutive value of the `counter`, then bytes `Utils.fromHex("0123456789abcdef0123456789abcdef");` placed in positions 16 and 0 respectively and encrypted with these IVs are exactly the same. This clearly shows, that IV, used to encrypt second 16 bytes with the first counter, is exactly the same as IV, used to encrypt first 16 bytes with the second counter. I.e. the IV is reused, making the protocol completely unsafe.

**Comment by levlam** [comment]
@murillo128 No, if the counter can be the same for different keyId.

**Comment by murillo128** [comment]
keys should be different if different keyId (it is up to the app to ensure it), so the iv will not not be reused within the same key

**Comment by levlam** [comment]
@murillo128 No, it will lead to exactly the same issue, if keyId are close enough.

**Comment by murillo128** [comment]
(I have deleted previous comment because it was inexact)

keyId is used as senderId, each sender should have different keys, so iv will not be reused for same sender/key

**Comment by levlam** [comment]
@murillo128 
> IV contains the keyId and the frame counter to ensure uniquenes when using same encryption key for all participants.

When all participants use the same key and different but close enough keyId, there will be exactly the same issue.

**Comment by murillo128** [comment]
While using the same encryption key for all users is allowed by the library, using a key per participant is strongly recommended.

**Comment by levlam** [comment]
If you don't want to support the same encryption key for all participants, you don't need keyId at all.

If the protocol is vulnerable when the same encryption key is used by all participants, then the protocol doesn't support the same encryption key for all participants and this should be clearly documented.

**Comment by murillo128** [comment]
I still have pending the update to the latest draft (I will do when new version is released to ensure not having to implement intermediate versions).

I have removed the comment about single key for all participants, as it has proven to be insecure.
