### ISSUE TITLE
Sign encoded frames doesn't work because a Bug using a Map.

### ISSUE THREAD

**Issue by ggoldens** [medooze/sframe#9]
On the Sender class, a Map is being used to accumulate pending encrypted frames so that after 10 frames a signature is generated.
The issue found is that the map is being used as a regular object, and not as a Map
https://github.com/medooze/sframe/blob/master/lib/Sender.js#L42 
```
//If we don't have the ssrc
if (!this.pending[ssrcId])
  //Create new pending frames array
  this.pending.set(ssrcId,[]);
```
Since `this.pending[ssrcId]` is always undefined, the value for the key ssrcId will be always be set as an empty array, so it will never sign any frame.

The solution is to use the .has() method of Map instead.

**Comment by ggoldens** [comment]
Hi @murillo128! What do you think about this fix?

**Comment by murillo128** [comment]
sorry, I have missed this! 

Yes, it seems the correct fix.  I will commit it tomorrow
